### ISSUE TITLE
Admin Activity Tracking - enhancements

### ISSUE THREAD

**Issue by amcclain** [xh/hoist-react#1981]
## "Small"
- [x] For day timeseries chart, fill in all days with zero metrics so you can e.g. more accurately read the chart and see days without visits. Right now we only draw points for days where we have data, so the shape is misleading.
- [x] Clicking on a chart node should select the corresponding aggregate grid row for easier exploration of the data.
- [x] Switch timeseries chart to `step` mode (I think this will look better, provide a more accurate view)
- [x] Make left agg report panel wider by default, or some other solution for shorter / smaller chart button labels so they don't so easily overflow
- [x] Display highly visible warning when query has been topped due to max rows limit on the controller

## Medium
- [ ] Query params in hoist-core are inserted into SQL surrounded by `%` for "contains" matching - but for the params where we offer a lookup drop-down we really want an exact match to support cases like having two categories "App" and "App Security". I left it as it was to avoid a breaking change, but we could support "exact" versions of the params, or just not worry about older HR clients that take the latest HC - they would just need to type carefully....

## Bigger
- [ ] Think about options for category management over time.  It seems problematic that you might have chosen a bad category name or temporarily had some category in place briefly that you want to now leave behind, and yet it will forever appear in the lookups dropdown.  Lookups could respect date query (which they don't now), or we could have some kind of filter, or we could even support changing the track data in bulk somehow, maybe in a tactical way (e.g. support category or message renames only via a dedicated endpoint that admins could hit directly)
- [ ] Explore having the chart optionally follow the grid selection, so you could chart metrics "one level down" by selecting a group row and having the chart display as if that group were the root.

**Comment by lbwexler** [comment]
This is a very old ticket Pete -- would like to see what is still relevant and make whatever changes make sense, with an eye toward closing this.  

It may be that certain things are obsolete or don't make sense any more.

**Comment by lbwexler** [comment]
Pete took care of the smaller nits -- thanks Pete!

**Comment by amcclain** [comment]
Closing this older (and mostly done) umbrella ticket in favor of more specific #3572 for server-side query support

I also still like the idea of a bulk category change for past track statements, to allow for updates to a category name you got kind of wrong, but will hold off entering a ticket on that as I can't say it's actually come up from a client request AFAIK
